### ISSUE TITLE
Spelling Error in Default Checks.yml

### ISSUE THREAD

**Issue by delbertina** [jiangdashao/Matrix-Issues#1452]
"matrix notify %player% tried to **bride** blocks quickly (Scaffold)"

I assume this is supposed to say break or something instead of bride. Cannot find a definition for "bride" used as a verb that isn't related to wedding stuff.

Relevant Config Section 
```
## Scaffold check
# Check prevents player bridging blocks or towering up faster than normal speed
scaffold:
  # Enable this check
  enable: true

  # Cancel VL
  cancel_vl: 15

  # Modules
  modules:
    # It can detect player bridging faster
    scaffold:
      enable: true
      vl_weights:
        safewalk: 4
        expand: 3
        limit: 1
        head: 5
        simple: 3
        direction: 4
    # It can detect player towering up faster
    tower:
      enable: true
      vl_weight: 2

  # Violation Thresholds
  # number_of_violations: '<command>'
  commands:
    7: 'matrix notify %player% tried to bride blocks quickly (Scaffold)'
    15: 'matrix notify %player% tried to bride blocks quickly (Scaffold) #2'
    #24: 'matrix kick %player% Scaffold/Tower'
```
