### ISSUE TITLE
[REQUEST] Make punishment commands support math

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#241]
# What features/checks do you need?
In checks.yml, this is what a check looks like:

```yml
speed:
  enable: true
  cancel_vl: 30
  entity_speed: true
  sprint_direction: true

  commands:
    50: 'matrix notify %player% tried to move faster than usual (Speed)'
```

After 50 violations, the matrix notify command is executed.
After that, no other punishment commands are executed.

My request is an option for math to be supported for violations.
Examples are below.

```yml
commands:
  5*2: 'matrix notify %player% tried to move faster than usual (Speed) #1'
  Will notify when the violations are 5, 10, 20, 40, 80

  5+3: 'matrix notify %player% tried to move faster than usual (Speed) #1'
  Will notify when the violations are 5, 8, 11, 14, 17...
```

*Thanks to @True-cc*
