### ISSUE TITLE
[REQUEST] Better, Reasonable Features

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#336]
**What features/checks do you need?:**

**Improve Chat Protection**
*Added blocked_commands and blocked_words.*
```
############################################################
#
#                       Chat Spam
#
# Description: Check prevents a player from spamming
# messages in the servers chat.
#
############################################################
chat:
  # Enable this check?
  enable: true

  # Minimum amount of time between messages (Seconds)
  min_time: 3

  # Number of violations to start canceling messages from being sent
  cancel_vl: 3
  
  # Blocked commands
  blocked_commands:
    1. plugins
    2. version
    3. about
  
  # Blocked words
  blocked_words:
    1. nigger
    2. bitch
    3. asshole

  # Punish Commands
  # number_of_violations: '<command>'
  commands:
    4: 'matrix notify %player% is spamming the chat (ChatSpam)'
    10: 'matrix kick %player% Stop spamming the chat!'
```
	
**MySQL Support**
*Added mysql.yml into the Matrix folder.*
```
host: 127.0.0.1
user: username
password: password
database: database1
table: matrix_logs
```

**Dynamic Check Names**
*Change the name of a check when it appears in alerts.*
*Added name: 'Velocity'*
```
############################################################
#
#                  Velocity / Anti-Knockback
#
# Description: Check prevents the player from using any type
# of anti-knockback hacks.
#
############################################################
velocity:
  # Name of check that appears in alerts
  name: 'Velocity'

  # Enable this check?
  enable: true

  # Modules List
  # You can turn off some velocity modules here
  # Set it to false to disable the module
  modules:
    vertical: true
    horizon: true
    air: true
    air_direction: true
    delay: true

  # Punish Commands
  # number_of_violations: '<command>'
  commands:
    10: 'matrix notify %player% tried to ignore server velocity (Anti-Knockback)'
    15: 'matrix notify %player% tried to ignore server velocity (Anti-Knockback) #2'
    20: 'matrix kick %player% Velocity/Anti-Knockback Hacks'
```

**Per World Checks**
*Configure in which worlds a "certain" check will be disabled.*
*Added disabled_worlds.*
```
############################################################
#
#                ChestSteal / InventoryMove
#
# Description: Check prevents the player from using illegal
# inventory modifications such as Steal. Also prevents quick
# inventory movement hacks.
#
############################################################
inventory:
  # Enable this check?
  enable: true
  
  # Worlds that this check won't run in
  disabled_worlds: 'test'

  # Number of violations to start canceling the movement of items
  cancel_vl: 10

  # Disable InventoryMove check
  # If you don't need InventoryMove check, you can set this to 'true' to disable it
  # This option ONLY works for 1.12/1.13/+ server
  disable_invmove: false

  # Punish Commands
  # number_of_violations: '<command>'
  commands:
    10: 'matrix notify %player% moved items in inventory too quickly (ChestSteal)'
    20: 'matrix kick %player% ChestSteal/Inventory Hacks'
```

**Customizable Verbose Messages**
*Added in language.yml.*

```
#########################################################################################################
#
#
#                                       Matrix Anti-Cheat
#                                         language.yml
#
#                             This file contains all the formatting
#                          options for the way Matrix talks to Players
#
#                         Proofreading/Translation By: DJRedNightMC#6027
#             Free & Paid Plugin Proofreading for Non-Native English Speaking Developers
#
#########################################################################################################

# Message Prefix
# Description: How would you like the Matrix prefix formatted?
prefix: '&7[&fMatrix&7]&r '

# Verbose Messages
# Description: How would you like the verbose messages formatted?
# Default: '%prefix%&7%player% failed &c%check% check &8| &7%type%  &b(+%added_vls%) &8| &7vl:%vls% ping:%ping% tps:%tps%'
# Styled: %prefix%&f%player% &7failed &f%check% &c(x%vls%) &7(TPS: %tps%) (Ping: %ping%) &8(%type% | %info%)

verbose: '%prefix%&7%player% failed &c%check% check &8| &7%type% %info% &b(+%added_vls%) &8| &7vl:%vls% ping:%ping% tps:%tps%'
```
